[2020-10-21 23:11:43,615] WARN Attempting to send response via channel for which there is no open connection, connection id fe80:0:0:0:2067:871c:2648:42b5%19:9092-fe80:0:0:0:2067:871c:2648:42b5%19:61193-2 (kafka.network.Processor)
[2020-10-21 23:11:44,356] WARN Client session timed out, have not heard from server in 2188659ms for sessionid 0x100167948f40001 (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:46,352] INFO Client session timed out, have not heard from server in 2188659ms for sessionid 0x100167948f40001, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:47,865] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:47,998] INFO Socket connection established, initiating session, client: /0:0:0:0:0:0:0:1:61269, server: localhost/0:0:0:0:0:0:0:1:2181 (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:48,000] WARN Unable to reconnect to ZooKeeper service, session 0x100167948f40001 has expired (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:48,001] INFO [ZooKeeperClient Kafka server] Session expired. (kafka.zookeeper.ZooKeeperClient)
[2020-10-21 23:11:48,000] INFO EventThread shut down for session: 0x100167948f40001 (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:48,003] INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient)
[2020-10-21 23:11:48,001] INFO Unable to reconnect to ZooKeeper service, session 0x100167948f40001 has expired, closing socket connection (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:48,006] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@7334aada (org.apache.zookeeper.ZooKeeper)
[2020-10-21 23:11:48,009] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2020-10-21 23:11:48,011] INFO zookeeper.request.timeout value is 0. feature enabled= (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:48,013] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:48,015] INFO Socket connection established, initiating session, client: /127.0.0.1:61272, server: localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:48,221] INFO Creating /brokers/ids/0 (is it secure? false) (kafka.zk.KafkaZkClient)
[2020-10-21 23:11:48,268] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x100167948f40005, negotiated timeout = 18000 (org.apache.zookeeper.ClientCnxn)
[2020-10-21 23:11:48,372] INFO Stat of the created znode at /brokers/ids/0 is: 252,252,1603303908270,1603303908270,1,0,0,72082304208732165,200,0,252
 (kafka.zk.KafkaZkClient)
[2020-10-21 23:11:48,372] INFO Registered broker 0 at path /brokers/ids/0 with addresses: PLAINTEXT://DESKTOP-3DEOF7P:9092, czxid (broker epoch): 252 (kafka.zk.KafkaZkClient)
